# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 菁菁者莪
email: laddiexu@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 格物、致知、诚意、正心、修身、齐家、治国、平天下
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laddiexu.github.io" # the base hostname & protocol for your site
github_username:  laddiexu

# Build settings
markdown: kramdown

# Add config for hit times support by leancloud
leancloud:
  enable: true
  app_id: lNCEwoorTi8rS3x1Kh4b27ii-gzGzoHsz
  app_key: XcYIXUHsr4Eg6Rj92g4PgJAS
  